### ISSUE TITLE
Integration with PyPI and conda for easier installation.

### ISSUE THREAD

**Issue by jo-mueller** [oncoray/mirp#2]
I found that MIRP relies on subpackages of scipy (I think stats), the existence of which depends strongly on the used python distribution.
In my case, I found that (re-)installing scipy and numpy with conda didn't work, but a forced reinstallation of scipy with pip did the trick. Maybe it's a specific version of scipy that's needed?

**Comment by alexzwanenburg** [comment]
This is true. Package requirements are noted in requirements.txt. Scipy version 1.3 or greater is required.

I am planning to introduce mirp on conda-forge as well so that installing mirp with the correct versioning is less of a hassle.

**Comment by codingS3b** [comment]
But as of right now, something like (untested)
```bash
pip install -r requirements.txt
python setup.py install
```
should also work fine (as long as the requirements are still up-to-date in the file)

**Comment by jo-mueller** [comment]
> pip install -r requirements.txt

Oh - ok, I'm dumb. Wasn't aware that installing the packages worked like that with pip.

**Comment by codingS3b** [comment]
I just noticed, that the python version is part of the requirements.txt which should not be that way since it leads to errors when running `pip install -r requirements.txt`, so please remove that line which states `python>=3.7`

**Comment by codingS3b** [comment]
why did you reopen the issue? Was there some problem I did not see initially?

**Comment by alexzwanenburg** [comment]
Yes, the main issue is still open. MIRP should be integrated with conda-forge and PyPI so that MIRP can be easily installed using package managers.

**Comment by alexzwanenburg** [comment]
Version 2.0.0 is now live on PyPI!
