### ISSUE TITLE
ImageClass: Interpolate_missing_slices can produce nan values

### ISSUE THREAD

**Issue by codingS3b** [oncoray/mirp#24]
I just hit a possible bug within mirp that produces `np.nan` values in the voxel grids of the images when doing interpolation of missing slices.

The problem is that when computing new slice positions via (see [here](https://github.com/oncoray/mirp/blob/86bce107e51dd654245cae013473c7de355beb35/mirp/imageClass.py#L359))
```py
new_slice_positions = np.arange(0.0, self.slice_position[-1] + self.spacing[0], self.spacing[0])
```
it can happen that the last element of `new_slice_positions` is larger than the last value of the `self.slice_positions` which leads to `np.nan` values on interpolation since we basically attempt extrapolation instead.

The example where I observed that was with values

```py
slice_position = np.array([0, 5, 10, 15, ..., 185, 485.57977])  # length 39
spacing[0] = 5
new_slice_positions = np.array([0, 5, 10, 15, ...., 485, 490]) # length 99, computed according to above command
x = slice_position
y = np.array([-1000] * len(x))
interpolator = Akima1DInterpolator(x=x, y=y)

new_vals = interpolator(new_slice_positions)
```

I think a check is needed to maybe discard elements in `new_slice_positions` that are out of the range of the original slice positions. @alexzwanenburg, what do you think about this?

Maybe adding 
`new_slice_positions = new_slice_positions[new_slice_positions <= self.slice_position[-1]]`
would already help?

**Comment by alexzwanenburg** [comment]
This should now be fixed on dev_ibsi_2.

**Comment by codingS3b** [comment]
Ah okay, great, then I was just not using an up-to-date version. Thanks.
