### ISSUE TITLE
Can we calculate the radiomic feature maps using mirp tool?

### ISSUE THREAD

**Issue by JZK00** [oncoray/mirp#25]
When we select the radiomic features, it's necessary to calculate the feature map using the radiomic features. And can we develop it using MIRP?

**Comment by alexzwanenburg** [comment]
Feature maps are currently not supported in MIRP, sorry. CERR (https://github.com/cerr/CERR) might be able to generate the maps you require.

I currently do not have the time to implement feature maps in a way that would be still be performant.

**Comment by JZK00** [comment]
Thanks for your reply. I will have a try.
