### ISSUE TITLE
Use of .dcm File Throws error.

### ISSUE THREAD

**Issue by neerajaj96** [oncoray/mirp#33]
On providing a dicom file and mask as input (https://github.com/theibsi/data_sets/tree/master/ibsi_1_digital_phantom/dicom), it throws the following error from 105 th line of dicomImport.py

Could not broadcast input array from shape(4,4,5) into shape(4,5)

**Comment by alexzwanenburg** [comment]
I will check this out. The NifTI variant of the phantom should work -- that phantom is used to check IBSI compliance as part of integration tests.

**Comment by alexzwanenburg** [comment]
The current state of the code now likely allows for processing that phantom.

- [ ] Add IBSI 1 test using the digital phantom in DICOM format.

**Comment by alexzwanenburg** [comment]
It actually works. However spacing and slice distance are incorrectly set in both image and mask files, whereas origin (or orientation) are incorrect for the mask. See theibsi/data_sets#2.
