### ISSUE TITLE
Slow parallellisation performance using the ray package

### ISSUE THREAD

**Issue by alexzwanenburg** [oncoray/mirp#41]
A user reported unexpected slow parallelisation performance, with the following symptoms:

- Low core usage.
- Implementing parallelisation using the `joblib.Parallel` package resolved the issue.

The following reasons may be excluded:

- Low memory availability.
- Concurrent processes on workstation.
- Large overhead vs. process times. Process times are in the order of minutes.

Causes to be tested:

- Inner parallelisation through the use of BLAS, MKL and the like by external packages such as `numpy`. The `joblib.Parallel` package automatically sets environment variables to limit inner parallelisation to available resources, but `ray` may not. `mirp` sets these environment variables on the main process upon initialisation, but `ray` might not copy or fork these into the parallel processes.

**Comment by peterneher** [comment]
Probably related: in my case, only one CPU seems to be used, while ray is initialized with 16 CPUs. Not sure what is parallelized, though. I am testing with a single map/mask image. The mask image contains multiple (15) labels.

**Comment by alexzwanenburg** [comment]
> Probably related: in my case, only one CPU seems to be used, while ray is initialized with 16 CPUs. Not sure what is parallelized, though. I am testing with a single map/mask image. The mask image contains multiple (15) labels.

`mirp` currently does not parallellize over masks. If only one image is provided, only one thread will be used. The behaviour you observed is expected.
