### ISSUE TITLE
Mask/image as numpy error

### ISSUE THREAD

**Issue by peterneher** [oncoray/mirp#42]
Passing a mask or an image as numpy instead of a file string to `extract_features` results in the following error (mirp 2.0.0):

FileNotFoundError: The mask file could not be found at the expected location: None

**Comment by alexzwanenburg** [comment]
Thanks for reporting! I will need to see if I can replicate the error.

- [ ] Add unit test for reading and importing numpy data directly. Current tests for reading and importing numpy files are present, but not for numpy data.
- [ ] Add unit test for extracting features from numpy data.

**Comment by alexzwanenburg** [comment]
The error was fixed.
