### ISSUE TITLE
supported matrix

### ISSUE THREAD

**Issue by drcandacemakedamoore** [oncoray/mirp#67]
As support for ray on Windows is experimental, last I checked, it isn't clear if this package is meant to run on Windows or not. Can you include a supported matrix to awnser questions of conda python and pypi python on one axis and OS on the other? 

below is an example

  | Linux | Win | OSX
-- | -- | -- | --
pyth  | Supported | Unknown | Unknown
 conda | Unknown | Unknown | Unknown

**Comment by alexzwanenburg** [comment]
I can confirm `ray` works on Windows. Would you like to see such a matrix for `ray` or for MIRP itself?

**Comment by drcandacemakedamoore** [comment]
I meant just for your package. No one should expect you to have to keep track of ray; but if you see in testing it starts breaking stuff apart for a certain OS/distribution combination (could happen) then consider moving that combination to something other than supported. Maybe under development until it catches up to a fix.

**Comment by alexzwanenburg** [comment]
I added matrix to the readme. The aim is to automate the matrix with GitHub workflow badges, once GitHub supports the creation of multiple badges from a matrix workflow.
