### ISSUE TITLE
dependencies specification

### ISSUE THREAD

**Issue by drcandacemakedamoore** [oncoray/mirp#79]
Your dependencies are clear to see in the pyproject.toml, but I would put a max on all of them. I'm hoping the package is around for a while, and if you have a whole full version number up i.e. 1.2.3 to 2.0.0, then it will potentially break things. It may sound theoretical, but as it has happened to me, it is a pet peeve. There should be a max version in the dependency.

**Comment by alexzwanenburg** [comment]
I see you point. Major version increases can introduces breaking changes in `mirp`. However, I don't think setting a max version for dependencies is the best solution for this issue, as in the past also minor version increments have produced breaking changes and errors (looking at you `numpy` 👀).

I think the better solution would be to have a biweekly or monthly action on the main branch to see if any errors (or deprecation warnings) pop up: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

What do you think?

**Comment by drcandacemakedamoore** [comment]
I think this can be a solution. I'll check to see if it is implemented before I sign off my review ;)
