### ISSUE TITLE
Consider adding DICOM attributes to feature extraction output

### ISSUE THREAD

**Issue by kirbyju** [oncoray/mirp#87]
Please use the below template to submit your issue:

# Expected behaviour

In the output of extract_features() when working with DICOM data I think it would be helpful to add image_series_description, image_series_instance_uid, mask_series_description, and mask_series_instance_uid columns.  It may also be worth including image_study_description and image_study_date.  This would make it easier to see which images/masks were being analyzed in datasets that contain multiple RTSTRUCT tumor segmentations per subject (e.g. the annotated [TCIA CPTAC collections](https://wiki.cancerimagingarchive.net/display/Public/CPTAC+Imaging+Proteomics).  In many cases the same tumor was annotated in multiple scans which resulted the same sample_name and image_mask name.

# Observed behaviour

Only sample_name, image_modality and image_mask_name were provided as a way to identify the extraction results.

# Steps to reproduce the problem

You can find sample data to reproduce this at https://doi.org/10.7937/SKQ4-QX48.  

# Specifications

- MIRP version: 2.2.1
- Python version: 3.8.11
- Operating system: MacOS Sonoma 14.4.1
- Other package versions (*if relevant*):

**Comment by alexzwanenburg** [comment]
This is something that can and should be addressed. Other use cases:
- show file name of NIfTI mask files that may have the same label (e.g. `1`) for different masks.
- show SUV type or PET units for PET imaging.

Note to self:
The tricky part here is to package metadata that are not an explicit attribute of `GenericImage` class in the `GenericImage` object created using `to_object`. Then `promote` is used to convert the `GenericImage` object to an inheriting class, e.g. `PETImage`, by wrapping `update_from_template`. `update_from_template` takes the attributes from one object and applies it to another. Currently such attributes are shared between the different classes.

Among the different ways to handle this, the following is probably the most straightforward.

- [ ] Add a `metadata` attribute to `GenericImage` that is simply a `dict` created from keyword arguments in that are not used by `GenericImage.__init__` (or `BaseMask.__init__`) in `to_object` methods.
- [ ] This `metadata` attribute is then copied using `update_from_template`. This can be safely done as these `metadata` are not altered during processing (unlike e.g. `image_origin`).
- [ ] `StandardWorkflow._get_feature_set_details` should be updated to generate the entries based on `GenericImage` and `BaseMask` attributes and `metadata`. Inheriting classes such as `PETImage` may then override these methods to extract additional metadata.

**Comment by alexzwanenburg** [comment]
Note that this is also a useful step towards exporting feature values in different formats (e.g. yaml), because this can be handled by the same framework.
