### ISSUE TITLE
AttributeError: module 'matplotlib.pyplot' has no attribute 'register_cmap' through matplotlib version 3.9.0 

### ISSUE THREAD

**Issue by smaginmi** [oncoray/mirp#93]
Please use the below template to submit your issue:

# Expected behavior

I'm running through this [TCIA_MIRP notebook](https://github.com/kirbyju/TCIA_Notebooks/blob/main/TCIA_MIRP.ipynb) and when running this snippet:
```
images = extract_images(image = image_path, 
                            mask = seg_path,
                            roi_name = "GTV_Mass",
                            image_export_format = "native")
# followed by 

image, mask = images[0]
image[0].show(mask=mask[0], slice_id=10)
```
And it should just show the image with mask of the mass. 

# Observed behavior

But instead of the image I get this error msg:
```
File ~/.venv/lib/python3.10/site-packages/mirp/_images/utilities.py:82, in InteractivePlot.__init__(self, image, mask, slice_id)
     76 # Create mask.
     77 if show_mask:
     78     # Define color map. The custom color map goes from transparent black to semi-transparent green and is
     79     # used as an overlay.
     80 
     81     # Create map and register
---> 82     plt.register_cmap(
     83         cmap=LinearSegmentedColormap(
     84             "mask_cm",
     85             {
     86                 'red': ((0.0, 0.0, 0.0), (1.0, 0.0, 0.0)),
     87                 'green': ((0.0, 0.0, 0.0), (1.0, 0.6, 0.6)),
     88                 'blue': ((0.0, 0.0, 0.0), (1.0, 0.0, 0.0)),
     89                 'alpha': ((0.0, 0.0, 0.0), (1.0, 0.4, 0.4))
     90             }
     91         ),
     92         override_builtin=True
     93     )
     95     self.mask_layer = self.axes.imshow(
     96         self.mask_data[self.slice_index, :, :],
     97         vmin=0.0,
     98         vmax=1.0,
     99         cmap="mask_cm"
    100     )
    101 else:

AttributeError: module 'matplotlib.pyplot' has no attribute 'register_cmap'
```

# Steps to reproduce the problem

The problem seems to stem from the matplotlib version (3.9.0) and downgrading to 3.7.0 and restarting the kernel solves my issue.  Here is a similar problem from a different project for reference [thread](https://github.com/DeepLabCut/DeepLabCut/pull/2583), where their solution is to pin their matplotlib to 3.8.x. 

# Specifications

- MIRP version: 2.2.3
- Python version: Python 3.10.12
- Operating system: Ubuntu 22.04.4 LTS

**Comment by alexzwanenburg** [comment]
Thanks for reporting this issue and providing a good indication of how to resolve it.

To do:
- [ ] Check in which version of `matplotlib` the `register_cmap` function was deprecated.
- [ ] Add a version check in places that currently use `register_cmap`, and register the colour map in newer versions according to [this example](https://matplotlib.org/stable/users/explain/colors/colormap-manipulation.html#registering-a-colormap).

**Comment by alexzwanenburg** [comment]
The breaking change was introduced in `matplotlib` [version 3.9.0](https://matplotlib.org/3.9.0/api/prev_api_changes/api_changes_3.9.0.html#top-level-cmap-registration-and-access-functions-in-mpl-cm)
